### ISSUE TITLE
Cloud Computing

### ISSUE THREAD

**Issue by Watch-Video** [patademahesh/Distributed-Video-Transcoding#1]
this Script is gorgeous !

Exist any solution to use this for computing on Amazon EC2 Cloud Services ?

Regards Sascha

**Comment by patademahesh** [comment]
Thanks a lot sascha.

No, currently there is no service available on AWS now. These scripts will require only plain Ubuntu or redhat  ec2 instances with some basic packages.

**Comment by patademahesh** [comment]
If you want i can heLP you with  the installation part.

**Comment by Watch-Video** [comment]
I mean does it Works on Amazon ec2 ?

**Comment by patademahesh** [comment]
Yes.
