### ISSUE TITLE
Splitt issues

### ISSUE THREAD

**Issue by rebotnix** [patademahesh/Distributed-Video-Transcoding#2]
hi,

i tested the script and i´m wondering if you maybe notice that a simply split with -ss = starttime and -t = length will produce audio issues in aac media streams when they get concated.  

a simple split at second 3 by starting time 0 for segment one and starting time at second 3 + another length of 3 is not frame and sync accurate.

when i look at the log files i saw this error during the concated process:
TS -830103474726726784, next:2959489 st:0 invalid dropping
PTS -830103474726720768, next:2959489 invalid dropping st:0
[mp4 @ 0x7fde9a035400] pts has no value
DTS -830103474726723840, next:2992856 st:0 invalid dropping
PTS -830103474726708736, next:2992856 invalid dropping st:0
[mp4 @ 0x7fde9a035400] pts has no value
DTS -830103474726720768, next:3026223 st:0 invalid dropping
PTS -830103474726714752, next:3026223 invalid dropping st:0
DTS -830103474726717824, next:3059590 st:0 invalid dropping
[mp4 @ 0x7fde9a035400] pts has no value
DTS -
....cut

do you have noticed that?

i think a real splich and stich function requires a lot more todo so that this will work perfectly. my idea is that you first have to extract the complete aac stream, then the video frames (best transmux video segments at keyframes positions). then encode the segments, then encoder audio, then mux all together.

i´m using fffmpeg (latest git) and maybe there the concat of avconv works better/other?

What do you think? Do i oversee something?

**Comment by patademahesh** [comment]
No I have never noticed this because, I haven't seen any audio issues in converted videos.

I have never used acvonv so don't have much idea.

**Comment by rebotnix** [comment]
thanks for your response.

can you please confirm that the basics ffmpeg part that your script is doing is this:

splitting with transcoding:
./ffmpeg -ss 0 -i input.mp4 -t 3 -vcodec libx264 -acodec aac -bsf:v h264_mp4toannexb -f mpegts -strict experimental -y part1.ts

./ffmpeg -ss 3 -i input.mp4 -t 3 -vcodec libx264 -acodec aac -bsf:v h264_mp4toannexb -f mpegts -strict experimental -y part1.ts

and so on with more parts...after transcoding...

muxing / merging back from nodes like:
./ffmpeg -y concat:part1.ts|part2.ts -c copy -bsf:a aac_adtstoasc -y merged.mp4

that´s it, right?

i think the reason why you don't hear the audio glitch is that when you only have 2 or 4 nodes and a playtime of , lets say 60  minutes, the first split is (lets say with 2 nodes) is at time position 30 minutes. 

When you seek to minute 29:50 wait till minute 30 you maybe will hear that split / audio glitch. i only tested with aac audio codecs, maybe other codecs are better for splitting. When you test with lower values, lets say split and merge every 3 seconds, then the glitches are more hearable. 

It would be nice when you can try this out, maybe with much smaller splits evey 3 seconds what i´m doing right now.

thanks for any help.

**Comment by patademahesh** [comment]
Yes you are right. This is the main ffmpeg logic.

I'll try this with very small video.

**Comment by patademahesh** [comment]
You are right there is some glitch while concatenating. Do you have any better way to do this ? 

Please suggest.

Thanks buddy.

**Comment by rebotnix** [comment]
no problem, i tought that it is not so easy to get split and stich working. another problem i have seen is that DTS and PTS seems not to concated right when you use the concat function in combination with ffmpeg, i had some success with resetting timestamps before concating, but thats another issue we have with video splitting vs. audio cutting.

for audio: my idea is to analyze the audio track with an filter plugin for the sample cut. normal audio with 44.100 HZ samples are not so easy to split, but possible. i tested it yesterday with an hacked own written audio filter plugin and it works. i will include the patch into the main ffmpeg repo and hope that the developers of ffmpeg will add this as well.

**Comment by paulm17** [comment]
I have a solution, according to SO:  https://stackoverflow.com/questions/46577437/ffmpeg-concat-drops-audio-frames  aac drops packets, which is why you get the gaps.

This fixed it for me.

-------

	// Break down file into segments by seconds
	ffmpeg -i test.mp4 -f segment -segment_time 150 -c copy -map 0 -copyts -muxdelay 0 test_%03d.ts &&

	// loop through each file and transcode it, keep pcm codec as aac drops packets
	for i in test_*.ts;
	  do name=`echo $i | cut -d'.' -f1`;
	  echo $name;
	  ffmpeg -i "$i" -codec:v libx264 -codec:a pcm_s16le -copyts -threads 6 "t_${name}.ts"
	done &&

	// rejoin segments into single file
	ls -v test_*.ts | xargs cat | ffmpeg -i - -c copy -movflags faststart output.mp4

**Comment by patademahesh** [comment]
@paulm17 Thanks for posting answer. But in this case you will end up changing audio codec to pcm_s16le. 

Correct me if i'm wrong.

**Comment by paulm17** [comment]
Nope, you are correct.  You have to use either pcm_s16le or flac as they won't suffer the same problem as aac.

Or if you want to avoid the issue another way.  use -codec:a copy.

If you read the SO answer.  You'll see why aac results in issues.

**Comment by patademahesh** [comment]
yes i read that. 
When to use -codec:a copy ? while generating ts ?

**Comment by paulm17** [comment]
no, when you transcode it.

Original: ffmpeg -i "$i" -codec:v libx264 -codec:a pcm_s16le

Use: ffmpeg -i "$i" -codec:v libx264 -codec:a copy

This is from memory, but I think its correct.

**Comment by patademahesh** [comment]
The another solution to this is, 

```
1. extract only audio from the source
2. split video(ts) without audio
3. concat ts
4. stitch audio extracted in first step
```
